// Default sneaker bucket list
const DEFAULT_SNEAKERS = [
  {
    id: '1',
    name: 'Air Max Ava Rover',
    brand: 'Nike',
    image: 'img/nike-ava-rover.jpg',
    colors: ['Black/White', 'Fossil Clay', 'Black Muslin'],
    price: 250,
    store: 'Nike Australia',
    storeLink: 'https://www.nike.com/au/a/ava-rover-release-info',
    status: 'want',
    size: 'US 10',
    priority: 4,
    notes: 'ReactX midsole. Street-ready performance runner.',
    dateAdded: '2026-07-06',
    datePurchased: null,
    pricePaid: null
  },
  {
    id: '2',
    name: 'BW Army',
    brand: 'Adidas',
    image: 'img/adidas-bw-army.jpg',
    colors: ['Cloud White', 'Off White', 'Core Black', 'Dark Brown'],
    price: 190,
    store: 'Adidas Australia',
    storeLink: 'https://www.adidas.com.au/bw-army-shoes/JR2002.html',
    status: 'want',
    size: 'US 10',
    priority: 5,
    notes: 'Clean everyday classic. Coated leather upper.',
    dateAdded: '2026-07-06',
    datePurchased: null,
    pricePaid: null
  },
  {
    id: '3',
    name: 'Speedcat OG McLaren',
    brand: 'Puma',
    image: 'img/puma-speedcat-mclaren.png',
    colors: ['White/Seafoam', 'Black/Papaya'],
    price: 200,
    store: 'Puma Australia',
    storeLink: 'https://au.puma.com/',
    status: 'want',
    size: 'US 10',
    priority: 5,
    notes: 'McLaren collab. Racing heritage. Very hyped.',
    dateAdded: '2026-07-06',
    datePurchased: null,
    pricePaid: null
  },
  {
    id: '4',
    name: 'Shox R4',
    brand: 'Nike',
    image: 'img/nike-shox-r4.jpg',
    colors: ['White/Metallic Silver', 'Black/Black', 'White/Comet Red'],
    price: 230,
    store: 'Nike Australia',
    storeLink: 'https://www.nike.com/au/',
    status: 'want',
    size: 'US 10',
    priority: 4,
    notes: 'Recrafted 2000s icon. Column cushioning.',
    dateAdded: '2026-07-06',
    datePurchased: null,
    pricePaid: null
  },
  {
    id: '5',
    name: 'Shox TL',
    brand: 'Nike',
    image: 'img/nike-shox-tl.jpeg',
    colors: ['White/Metallic Silver', 'Black/Max Orange', 'Pure Platinum'],
    price: 250,
    store: 'Nike Australia',
    storeLink: 'https://www.nike.com/au/',
    status: 'want',
    size: 'US 10',
    priority: 3,
    notes: 'Full-length Shox. Futuristic 2003 revived.',
    dateAdded: '2026-07-06',
    datePurchased: null,
    pricePaid: null
  },
  {
    id: '6',
    name: 'XLG Runner Deluxe',
    brand: 'Adidas',
    image: 'img/adidas-xlg-runner.jpg',
    colors: ['Core White', 'Silver Metallic', 'Black'],
    price: 200,
    store: 'Adidas Australia',
    storeLink: 'https://www.adidas.com.au/',
    status: 'maybe',
    size: 'US 10',
    priority: 3,
    notes: 'Chunky oversized runner. Trendy silhouette.',
    dateAdded: '2026-07-06',
    datePurchased: null,
    pricePaid: null
  },
  {
    id: '7',
    name: 'Adizero EVO SL',
    brand: 'Adidas',
    image: 'img/adidas-adizero-evo-sl.jpg',
    colors: ['Cloud White', 'Core Black', 'Lucid Blue', 'Burgundy'],
    price: 220,
    store: 'Adidas Australia',
    storeLink: 'https://www.adidas.com.au/adizero-evo-sl-shoes-mens/JH6206.html',
    status: 'want',
    size: 'US 10',
    priority: 4,
    notes: 'LIGHTSTRIKE PRO midsole. Racing-inspired lightweight.',
    dateAdded: '2026-07-06',
    datePurchased: null,
    pricePaid: null
  },
  {
    id: '8',
    name: 'Hyperboost Edge',
    brand: 'Adidas',
    image: 'img/adidas-hyperboost.webp',
    colors: ['Cloud White', 'Core Black', 'Pure Ruby'],
    price: 340,
    store: 'Adidas Australia',
    storeLink: 'https://www.adidas.com.au/hyperboost-edge-running-shoes/KI1913.html',
    status: 'want',
    size: 'US 10',
    priority: 3,
    notes: 'New Boost era. HyperBoost Pro midsole. 255g.',
    dateAdded: '2026-07-06',
    datePurchased: null,
    pricePaid: null
  },
  {
    id: '9',
    name: 'Cloudtilt',
    brand: 'On',
    image: 'img/on-cloudtilt.jpg',
    colors: ['Mineral/Ivory', 'Undyed/White', 'All Black', 'Fog/Umber'],
    price: 229,
    store: 'On Australia',
    storeLink: 'https://www.on.com/en-au/products/cloudtilt-m-3me1010',
    status: 'want',
    size: 'US 10',
    priority: 4,
    notes: 'Swiss engineering. CloudTec Phase. Ultra-light EVA.',
    dateAdded: '2026-07-06',
    datePurchased: null,
    pricePaid: null
  },
  {
    id: '10',
    name: 'Air Max Plus TN',
    brand: 'Nike',
    image: 'img/nike-air-max-plus-tn.jpg',
    colors: ['White/Cool Grey', 'Black/Volt', 'Triple Black'],
    price: 260,
    store: 'Nike Australia',
    storeLink: 'https://www.nike.com/au/',
    status: 'want',
    size: 'US 10',
    priority: 5,
    notes: 'Iconic Tuned Air. Need this one bad.',
    dateAdded: '2026-07-06',
    datePurchased: null,
    pricePaid: null
  }
];
